### PR TITLE
Fix variant size calculation

### PR DESCRIPTION
**Pull request by Arshia001**

### CODE REVIEW

**Review by ptitSeb — APPROVED** [review]

**Comment by ptitSeb** [comment]
quite tricky to follow, some comment could help future maintainers.

**Comment by Arshia001** [comment]
@ptitSeb please take another look. The implementation was still wrong, but now it should hopefully be correct. I also added comments.

**Review by ptitSeb — APPROVED** [review]
This is for handling stuff like:
```C
struct {
  uint8_t  tag;
  union {
   ....
  } payload;
} stuff;
```
I supose?

**Comment by Arshia001** [comment]
yes, it is.

**Pull request merged**
